In [1]:
import os
import zipfile
import subprocess

def download_kaggle_dataset(dataset_name: str, download_path: str):
    os.makedirs(download_path, exist_ok=True)

    result = subprocess.run(
        [
            "kaggle",
            "datasets",
            "download",
            "-d",
            dataset_name,
            "-p",
            download_path,
        ],
        capture_output=True,
        text=True,
    )

    if result.returncode != 0:
        raise Exception(result.stderr)

    # Extract zip files
    for file in os.listdir(download_path):
        if file.endswith(".zip"):
            zip_path = os.path.join(download_path, file)

            with zipfile.ZipFile(zip_path, "r") as zip_ref:
                zip_ref.extractall(download_path)

    print(f"Dataset downloaded to: {os.path.abspath(download_path)}")

In [2]:
dataset_name = 'uciml/sms-spam-collection-dataset'
download_path = './datasets'
download_kaggle_dataset(dataset_name, download_path)

Dataset downloaded to: /content/datasets

In [3]:
import pandas as pd

df = pd.read_csv(
    "./datasets/spam.csv",
    encoding="latin-1"
)

# Keep only useful columns
df = df[["v1", "v2"]]

# Rename columns
df.columns = ["label", "message"]

df.head()

  label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [4]:
# Data Cleaning and Preprocessing
import re
import nltk
nltk.download("stopwords")
nltk.download("wordnet")

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...

True

In [5]:
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

wl = WordNetLemmatizer()

In [6]:
corpus = []
for i in range(len(df)):
    review = re.sub("[^a-zA-Z]", " ", df["message"][i])
    review = review.lower()
    review = review.split()

    review = [
        wl.lemmatize(word)
        for word in review
        if word not in set(stopwords.words("english"))
    ]
    review = " ".join(review)
    corpus.append(review)

In [7]:
# Create Bag Of Words model
from sklearn.feature_extraction.text import CountVectorizer
# For Binary BOW enable binary=True
cv = CountVectorizer(max_features=2500, ngram_range=(1, 2))

In [8]:
# Independent Features
X = cv.fit_transform(corpus).toarray()

In [9]:
import numpy as np

np.set_printoptions(
    edgeitems=30,
    linewidth=100000,
    formatter={"float_kind": lambda x: "%.3g" % x}
)

In [10]:
cv.vocabulary_

{'go': np.int64(811),
 'point': np.int64(1614),
 'crazy': np.int64(447),
 'available': np.int64(112),
 'bugis': np.int64(227),
 'great': np.int64(856),
 'world': np.int64(2436),
 'la': np.int64(1096),
 'cine': np.int64(345),
 'got': np.int64(847),
 'wat': np.int64(2336),
 'ok': np.int64(1477),
 'lar': np.int64(1108),
 'joking': np.int64(1053),
 'wif': np.int64(2399),
 'oni': np.int64(1493),
 'free': np.int64(718),
 'entry': np.int64(616),
 'wkly': np.int64(2422),
 'comp': np.int64(401),
 'win': np.int64(2404),
 'cup': np.int64(455),
 'final': np.int64(683),
 'st': np.int64(1961),
 'may': np.int64(1267),
 'text': np.int64(2090),
 'receive': np.int64(1696),
 'question': np.int64(1662),
 'std': np.int64(1979),
 'txt': np.int64(2200),
 'rate': np.int64(1675),
 'apply': np.int64(77),
 'free entry': np.int64(723),
 'entry wkly': np.int64(618),
 'std txt': np.int64(1980),
 'txt rate': np.int64(2204),
 'rate apply': np.int64(1676),
 'dun': np.int64(571),
 'say': np.int64(1796),
 'early': np.int64(581),
 'already': np.int64(51),
 'nah': np.int64(1390),
 'think': np.int64(2110),
 'usf': np.int64(2265),
 'life': np.int64(1154),
 'around': np.int64(88),
 'though': np.int64(2118),
 'freemsg': np.int64(736),
 'hey': np.int64(917),
 'darling': np.int64(479),
 'week': np.int64(2365),
 'word': np.int64(2431),
 'back': np.int64(131),
 'like': np.int64(1159),
 'fun': np.int64(763),
 'still': np.int64(1982),
 'tb': np.int64(2069),
 'xxx': np.int64(2463),
 'send': np.int64(1830),
 'even': np.int64(629),
 'brother': np.int64(217),
 'speak': np.int64(1939),
 'treat': np.int64(2179),
 'per': np.int64(1540),
 'request': np.int64(1740),
 'melle': np.int64(1284),
 'set': np.int64(1847),
 'callertune': np.int64(273),
 'caller': np.int64(270),
 'press': np.int64(1636),
 'copy': np.int64(430),
 'friend': np.int64(743),
 'per request': np.int64(1544),
 'set callertune': np.int64(1848),
 'callertune caller': np.int64(274),
 'caller press': np.int64(271),
 'press copy': np.int64(1637),
 'copy friend': np.int64(431),
 'friend callertune': np.int64(744),
 'winner': np.int64(2409),
 'valued': np.int64(2274),
 'network': np.int64(1406),
 'customer': np.int64(461),
 'selected': np.int64(1822),
 'prize': np.int64(1644),
 'reward': np.int64(1752),
 'claim': np.int64(348),
 'call': np.int64(244),
 'code': np.int64(366),
 'valid': np.int64(2272),
 'hour': np.int64(960),
 'claim call': np.int64(349),
 'call claim': np.int64(248),
 'claim code': np.int64(350),
 'mobile': np.int64(1334),
 'month': np.int64(1353),
 'entitled': np.int64(614),
 'update': np.int64(2230),
 'latest': np.int64(1118),
 'colour': np.int64(380),
 'camera': np.int64(280),
 'co': np.int64(363),
 'entitled update': np.int64(615),
 'update latest': np.int64(2232),
 'latest colour': np.int64(1120),
 'free call': np.int64(721),
 'call mobile': np.int64(258),
 'mobile update': np.int64(1342),
 'update co': np.int64(2231),
 'co free': np.int64(364),
 'gonna': np.int64(832),
 'home': np.int64(944),
 'soon': np.int64(1926),
 'want': np.int64(2321),
 'talk': np.int64(2064),
 'stuff': np.int64(2015),
 'anymore': np.int64(67),
 'tonight': np.int64(2162),
 'enough': np.int64(610),
 'today': np.int64(2146),
 'chance': np.int64(318),
 'cash': np.int64(304),
 'pound': np.int64(1626),
 'cost': np.int64(433),
 'day': np.int64(485),
 'reply': np.int64(1727),
 'hl': np.int64(929),
 'info': np.int64(1001),
 'chance win': np.int64(320),
 'win cash': np.int64(2405),
 'reply hl': np.int64(1731),
 'hl info': np.int64(930),
 'urgent': np.int64(2254),
 'membership': np.int64(1287),
 'www': np.int64(2451),
 'net': np.int64(1404),
 'pobox': np.int64(1610),
 'ldnw': np.int64(1131),
 'week free': np.int64(2367),
 'txt word': np.int64(2206),
 'searching': np.int64(1808),
 'right': np.int64(1754),
 'thank': np.int64(2101),
 'promise': np.int64(1654),
 'wont': np.int64(2430),
 'take': np.int64(2060),
 'help': np.int64(915),
 'wonderful': np.int64(2428),
 'blessing': np.int64(182),
 'time': np.int64(2131),
 'date': np.int64(482),
 'sunday': np.int64(2031),
 'use': np.int64(2262),
 'credit': np.int64(449),
 'click': np.int64(357),
 'wap': np.int64(2333),
 'link': np.int64(1168),
 'next': np.int64(1420),
 'message': np.int64(1293),
 'http': np.int64(969),
 'com': np.int64(383),
 'oh': np.int64(1473),
 'watching': np.int64(2343),
 'eh': np.int64(592),
 'remember': np.int64(1719),
 'name': np.int64(1392),
 'yes': np.int64(2479),
 'naughty': np.int64(1397),
 'make': np.int64(1239),
 'wet': np.int64(2388),
 'fine': np.int64(690),
 'way': np.int64(2348),
 'feel': np.int64(671),
 'england': np.int64(606),
 'dont': np.int64(548),
 'miss': np.int64(1323),
 'goal': np.int64(822),
 'team': np.int64(2074),
 'news': np.int64(1419),
 'ur': np.int64(2233),
 'national': np.int64(1394),
 'eg': np.int64(590),
 'try': np.int64(2188),
 'wq': np.int64(2446),
 'dont miss': np.int64(550),
 'seriously': np.int64(1843),
 'going': np.int64(826),
 'ha': np.int64(883),
 'ha ha': np.int64(884),
 'pay': np.int64(1535),
 'first': np.int64(694),
 'da': np.int64(468),
 'stock': np.int64(1986),
 'comin': np.int64(396),
 'aft': np.int64(26),
 'finish': np.int64(692),
 'lunch': np.int64(1229),
 'str': np.int64(2008),
 'lor': np.int64(1200),
 'ard': np.int64(83),
 'smth': np.int64(1908),
 'alright': np.int64(52),
 'meet': np.int64(1278),
 'eat': np.int64(585),
 'really': np.int64(1691),
 'hungry': np.int64(974),
 'tho': np.int64(2117),
 'suck': np.int64(2024),
 'mark': np.int64(1251),
 'getting': np.int64(798),
 'worried': np.int64(2437),
 'know': np.int64(1089),
 'sick': np.int64(1870),
 'turn': np.int64(2196),
 'pizza': np.int64(1575),
 'lol': np.int64(1188),
 'always': np.int64(55),
 'catch': np.int64(310),
 'bus': np.int64(229),
 'egg': np.int64(591),
 'tea': np.int64(2072),
 'eating': np.int64(587),
 'mom': np.int64(1348),
 'left': np.int64(1139),
 'dinner': np.int64(529),
 'love': np.int64(1206),
 'amp': np.int64(58),
 'car': np.int64(292),
 'let': np.int64(1146),
 'room': np.int64(1765),
 'let know': np.int64(1148),
 'work': np.int64(2432),
 'feel like': np.int64(672),
 'wait': np.int64(2301),
 'sure': np.int64(2043),
 'live': np.int64(1174),
 'yeah': np.int64(2472),
 'child': np.int64(338),
 'till': np.int64(2130),
 'cheer': np.int64(335),
 'yeah got': np.int64(2473),
 'tell': np.int64(2079),
 'anything': np.int64(69),
 'tell anything': np.int64(2080),
 'quick': np.int64(1663),
 'thanks': np.int64(2102),
 'subscription': np.int64(2023),
 'ringtone': np.int64(1757),
 'uk': np.int64(2214),
 'charged': np.int64(326),
 'please': np.int64(1588),
 'confirm': np.int64(411),
 'replying': np.int64(1735),
 'mobile charged': np.int64(1336),
 'yup': np.int64(2498),
 'look': np.int64(1194),
 'timing': np.int64(2137),
 'msg': np.int64(1372),
 'learn': np.int64(1134),
 'nd': np.int64(1398),
 'lesson': np.int64(1145),
 'go home': np.int64(816),
 'oops': np.int64(1497),
 'roommate': np.int64(1766),
 'done': np.int64(547),
 'see': np.int64(1816),
 'letter': np.int64(1149),
 'decide': np.int64(502),
 'anything lor': np.int64(70),
 'hello': np.int64(914),
 'saturday': np.int64(1790),
 'texting': np.int64(2098),
 'decided': np.int64(503),
 'tomo': np.int64(2154),
 'trying': np.int64(2189),
 'pls': np.int64(1594),
 'ahead': np.int64(34),
 'wanted': np.int64(2331),
 'weekend': np.int64(2372),
 'abiola': np.int64(2),
 'great weekend': np.int64(858),
 'forget': np.int64(710),
 'need': np.int64(1402),
 'crave': np.int64(446),
 'sweet': np.int64(2053),
 'want need': np.int64(2326),
 'tried': np.int64(2180),
 'sm': np.int64(1901),
 'nokia': np.int64(1434),
 'camcorder': np.int64(276),
 'delivery': np.int64(512),
 'tomorrow': np.int64(2155),
 'call reply': np.int64(263),
 'free nokia': np.int64(729),
 'nokia mobile': np.int64(1439),
 'mobile free': np.int64(1339),
 'free camcorder': np.int64(722),
 'please call': np.int64(1589),
 'delivery tomorrow': np.int64(513),
 'seeing': np.int64(1819),
 'hope': np.int64(948),
 'man': np.int64(1244),
 'well': np.int64(2380),
 'lt': np.int64(1220),
 'gt': np.int64(863),
 'inch': np.int64(996),
 'lt gt': np.int64(1222),
 'missed': np.int64(1325),
 'missed call': np.int64(1326),
 'get': np.int64(786),
 'nigeria': np.int64(1425),
 'hopefully': np.int64(951),
 'tyler': np.int64(2211),
 'could': np.int64(438),
 'maybe': np.int64(1269),
 'ask': np.int64(97),
 'bit': np.int64(178),
 'hospital': np.int64(955),
 'kept': np.int64(1073),
 'telling': np.int64(2083),
 'weak': np.int64(2357),
 'want go': np.int64(2324),
 'saw': np.int64(1795),
 'class': np.int64(355),
 'first time': np.int64(695),
 'usually': np.int64(2268),
 'run': np.int64(1773),
 'half': np.int64(889),
 'almost': np.int64(48),
 'whole': np.int64(2396),
 'second': np.int64(1811),
 'like lt': np.int64(1162),
 'fyi': np.int64(766),
 'ride': np.int64(1753),
 'morning': np.int64(1358),
 'place': np.int64(1576),
 'wow': np.int64(2445),
 'never': np.int64(1410),
 'thought': np.int64(2119),
 'liked': np.int64(1163),
 'since': np.int64(1879),
 'best': np.int64(168),
 'happy': np.int64(899),
 'sorry': np.int64(1927),
 'give': np.int64(805),
 'ac': np.int64(5),
 'new': np.int64(1411),
 'red': np.int64(1704),
 'play': np.int64(1581),
 'ice': np.int64(980),
 'correct': np.int64(432),
 'end': np.int64(599),
 'sm ac': np.int64(1902),
 'yesterday': np.int64(2485),
 'find': np.int64(686),
 'congrats': np.int64(412),
 'year': np.int64(2475),
 'special': np.int64(1942),
 'cinema': np.int64(346),
 'pas': np.int64(1532),
 'etc': np.int64(625),
 'bx': np.int64(235),
 'ip': np.int64(1020),
 'pm': np.int64(1604),
 'etc free': np.int64(626),
 'bx ip': np.int64(236),
 'ip pm': np.int64(1021),
 'later': np.int64(1115),
 'meeting': np.int64(1280),
 'sorry call': np.int64(1928),
 'call later': np.int64(256),
 'later meeting': np.int64(1116),
 'reached': np.int64(1684),
 'pick': np.int64(1563),
 'move': np.int64(1364),
 'pain': np.int64(1523),
 'way home': np.int64(2350),
 'good': np.int64(834),
 'joke': np.int64(1052),
 'girl': np.int64(804),
 'situation': np.int64(1890),
 'part': np.int64(1528),
 'checking': np.int64(334),
 'iq': np.int64(1024),
 'took': np.int64(2164),
 'forever': np.int64(709),
 'come': np.int64(386),
 'ok come': np.int64(1478),
 'double': np.int64(553),
 'check': np.int64(332),
 'hair': np.int64(888),
 'said': np.int64(1782),
 'wun': np.int64(2450),
 'cut': np.int64(463),
 'short': np.int64(1862),
 'nice': np.int64(1423),
 'pleased': np.int64(1591),
 'following': np.int64(704),
 'review': np.int64(1751),
 'mob': np.int64(1332),
 'awarded': np.int64(120),
 'bonus': np.int64(188),
 'awarded bonus': np.int64(121),
 'prize call': np.int64(1645),
 'song': np.int64(1922),
 'frnds': np.int64(754),
 'rply': np.int64(1771),
 'send ur': np.int64(1836),
 'complimentary': np.int64(406),
 'trip': np.int64(2182),
 'dis': np.int64(533),
 'ur awarded': np.int64(2234),
 'hear': np.int64(908),
 'plane': np.int64(1578),
 'wah': np.int64(2300),
 'lucky': np.int64(1227),
 'save': np.int64(1794),
 'money': np.int64(1352),
 'hee': np.int64(912),
 'finished': np.int64(693),
 'hi': np.int64(921),
 'babe': np.int64(127),
 'im': np.int64(988),
 'wanna': np.int64(2320),
 'something': np.int64(1918),
 'xx': np.int64(2462),
 'hi babe': np.int64(922),
 'waiting': np.int64(2306),
 'call free': np.int64(250),
 'thats': np.int64(2105),
 'cool': np.int64(428),
 'respect': np.int64(1742),
 'thats cool': np.int64(2106),
 'people': np.int64(1539),
 'much': np.int64(1378),
 'pa': np.int64(1518),
 'looking': np.int64(1198),
 'job': np.int64(1046),
 'ta': np.int64(2059),
 'ah': np.int64(32),
 'hi hi': np.int64(924),
 'stop': np.int64(1990),
 'urgnt': np.int64(2260),
 'real': np.int64(1690),
 'yo': np.int64(2491),
 'ticket': np.int64(2128),
 'one': np.int64(1490),
 'used': np.int64(2263),
 'started': np.int64(1972),
 'came': np.int64(278),
 'bed': np.int64(160),
 'coin': np.int64(371),
 'gotta': np.int64(853),
 'kano': np.int64(1064),
 'il': np.int64(986),
 'download': np.int64(555),
 'wen': np.int64(2383),
 'wen ur': np.int64(2384),
 'stand': np.int64(1965),
 'close': np.int64(359),
 'another': np.int64(63),
 'night': np.int64(1426),
 'spent': np.int64(1951),
 'late': np.int64(1114),
 'afternoon': np.int64(27),
 'mean': np.int64(1271),
 'smile': np.int64(1904),
 'pleasure': np.int64(1592),
 'trouble': np.int64(2183),
 'rain': np.int64(1670),
 'sum': np.int64(2028),
 'hurt': np.int64(976),
 'someone': np.int64(1915),
 'smiling': np.int64(1905),
 'service': np.int64(1844),
 'representative': np.int64(1737),
 'guaranteed': np.int64(871),
 'call customer': np.int64(249),
 'customer service': np.int64(462),
 'service representative': np.int64(1846),
 'representative pm': np.int64(1739),
 'pm guaranteed': np.int64(1606),
 'guaranteed cash': np.int64(873),
 'cash prize': np.int64(308),
 'havent': np.int64(906),
 'planning': np.int64(1580),
 'buy': np.int64(232),
 'show': np.int64(1863),
 'simply': np.int64(1878),
 'password': np.int64(1533),
 'free ringtone': np.int64(732),
 'movie': np.int64(1365),
 'abt': np.int64(4),
 'wat abt': np.int64(2337),
 'load': np.int64(1179),
 'loan': np.int64(1180),
 'wk': np.int64(2420),
 'forgot': np.int64(711),
 'appointment': np.int64(78),
 'shower': np.int64(1866),
 'cause': np.int64(311),
 'prob': np.int64(1649),
 'need get': np.int64(1403),
 'get home': np.int64(791),
 'nothing': np.int64(1452),
 'else': np.int64(594),
 'okay': np.int64(1485),
 'price': np.int64(1639),
 'long': np.int64(1191),
 'ave': np.int64(113),
 'gone': np.int64(831),
 'driving': np.int64(564),
 'test': np.int64(2089),
 'yet': np.int64(2486),
 'guess': np.int64(879),
 'gave': np.int64(773),
 'boston': np.int64(198),
 'men': np.int64(1288),
 'changed': np.int64(322),
 'search': np.int64(1807),
 'location': np.int64(1182),
 'cuz': np.int64(465),
 'page': np.int64(1521),
 'umma': np.int64(2216),
 'lot': np.int64(1204),
 'dear': np.int64(498),
 'love lot': np.int64(1210),
 'wish': np.int64(2411),
 'birthday': np.int64(176),
 'making': np.int64(1242),
 'truly': np.int64(2185),
 'aight': np.int64(36),
 'hit': np.int64(927),
 'get cash': np.int64(788),
 'would': np.int64(2443),
 'address': np.int64(18),
 'computer': np.int64(407),
 'old': np.int64(1487),
 'better': np.int64(169),
 'worry': np.int64(2438),
 'busy': np.int64(231),
 'research': np.int64(1741),
 'thing': np.int64(2109),
 'scared': np.int64(1800),
 'mah': np.int64(1235),
 'contact': np.int64(417),
 'last': np.int64(1109),
 'draw': np.int64(556),
 'hr': np.int64(967),
 'ppm': np.int64(1630),
 'trying contact': np.int64(2190),
 'contact last': np.int64(420),
 'last weekend': np.int64(1113),
 'weekend draw': np.int64(2373),
 'draw show': np.int64(558),
 'show prize': np.int64(1864),
 'prize guaranteed': np.int64(1647),
 'guaranteed call': np.int64(872),
 'code valid': np.int64(369),
 'valid hr': np.int64(2273),
 'hr ppm': np.int64(968),
 'wa': np.int64(2299),
 'anyway': np.int64(73),
 'juz': np.int64(1062),
 'tt': np.int64(2192),
 'eatin': np.int64(586),
 'weight': np.int64(2377),
 'haha': np.int64(886),
 'happened': np.int64(895),
 'entered': np.int64(612),
 'cabin': np.int64(238),
 'bos': np.int64(196),
 'felt': np.int64(674),
 'askd': np.int64(98),
 'invited': np.int64(1015),
 'apartment': np.int64(74),
 'went': np.int64(2385),
 'entered cabin': np.int64(613),
 'cabin pa': np.int64(239),
 'pa said': np.int64(1519),
 'said happy': np.int64(1783),
 'happy day': np.int64(901),
 'day bos': np.int64(487),
 'bos felt': np.int64(197),
 'felt special': np.int64(675),
 'special askd': np.int64(1943),
 'askd lunch': np.int64(99),
 'lunch lunch': np.int64(1231),
 'lunch invited': np.int64(1230),
 'invited apartment': np.int64(1016),
 'apartment went': np.int64(75),
 'specially': np.int64(1947),
 'holiday': np.int64(940),
 'flight': np.int64(701),
 'inc': np.int64(995),
 'operator': np.int64(1499),
 'min': np.int64(1304),
 'winner specially': np.int64(2410),
 'specially selected': np.int64(1948),
 'selected receive': np.int64(1823),
 'speak live': np.int64(1940),
 'live operator': np.int64(1176),
 'operator claim': np.int64(1500),
 'must': np.int64(1387),
 'friday': np.int64(742),
 'hmm': np.int64(932),
 'uncle': np.int64(2220),
 'informed': np.int64(1003),
 'paying': np.int64(1537),
 'school': np.int64(1802),
 'directly': np.int64(532),
 'food': np.int64(706),
 'private': np.int64(1642),
 'account': np.int64(9),
 'statement': np.int64(1974),
 'identifier': np.int64(983),
 'expires': np.int64(650),
 'private account': np.int64(1643),
 'account statement': np.int64(10),
 'statement show': np.int64(1975),
 'call identifier': np.int64(252),
 'identifier code': np.int64(984),
 'code expires': np.int64(367),
 'landline': np.int64(1104),
 'box': np.int64(203),
 'urgent mobile': np.int64(2257),
 'mobile awarded': np.int64(1335),
 'bonus caller': np.int64(189),
 'caller prize': np.int64(272),
 'contact call': np.int64(418),
 'call landline': np.int64(255),
 'voda': np.int64(2290),
 'number': np.int64(1459),
 'ending': np.int64(601),
 'award': np.int64(118),
 'match': np.int64(1255),
 'quoting': np.int64(1668),
 'standard': np.int64(1966),
 'app': np.int64(76),
 'today voda': np.int64(2151),
 'voda number': np.int64(2291),
 'number ending': np.int64(1461),
 'ending selected': np.int64(602),
 'receive award': np.int64(1697),
 'match please': np.int64(1256),
 'call quoting': np.int64(262),
 'quoting claim': np.int64(1669),
 'code standard': np.int64(368),
 'standard rate': np.int64(1967),
 'mu': np.int64(1377),
 'buying': np.int64(233),
 'wat time': np.int64(2339),
 'time finish': np.int64(2133),
 'yetunde': np.int64(2488),
 'sent': np.int64(1839),
 'bother': np.int64(199),
 'sending': np.int64(1837),
 'del': np.int64(509),
 'bak': np.int64(138),
 'long time': np.int64(1192),
 'give call': np.int64(806),
 'dear call': np.int64(499),
 'answer': np.int64(65),
 'sunshine': np.int64(2035),
 'quiz': np.int64(1666),
 'top': np.int64(2165),
 'sony': np.int64(1923),
 'dvd': np.int64(578),
 'player': np.int64(1584),
 'country': np.int64(439),
 'sp': np.int64(1936),
 'sunshine quiz': np.int64(2036),
 'sony dvd': np.int64(1924),
 'dvd player': np.int64(579),
 'player know': np.int64(1585),
 'know country': np.int64(1091),
 'sp tyrone': np.int64(1937),
 'laid': np.int64(1100),
 'dogging': np.int64(544),
 'direct': np.int64(531),
 'join': np.int64(1049),
 'bt': np.int64(220),
 'txting': np.int64(2208),
 'nt': np.int64(1454),
 'ec': np.int64(588),
 'want get': np.int64(2323),
 'get laid': np.int64(792),
 'want real': np.int64(2328),
 'sent direct': np.int64(1840),
 'ur mob': np.int64(2245),
 'join uk': np.int64(1050),
 'haf': np.int64(885),
 'yijue': np.int64(2489),
 'chat': np.int64(329),
 'age': np.int64(30),
 'yr': np.int64(2494),
 'go get': np.int64(815),
 'lazy': np.int64(1127),
 'type': np.int64(2212),
 'lect': np.int64(1138),
 'sir': np.int64(1884),
 'mail': np.int64(1237),
 'sir waiting': np.int64(1885),
 'swt': np.int64(2057),
 'tired': np.int64(2138),
 'little': np.int64(1173),
 'lovable': np.int64(1205),
 'person': np.int64(1546),
 'coz': np.int64(443),
 'heart': np.int64(910),
 'gud': np.int64(874),
 'ni': np.int64(1422),
 'gud ni': np.int64(877),
 'open': np.int64(1498),
 'ya': np.int64(2465),
 'yes see': np.int64(2483),
 'whats': np.int64(2391),
 'taking': np.int64(2063),
 'replied': np.int64(1726),
 'sexy': np.int64(1851),
 'local': np.int64(1181),
 'luv': np.int64(1232),
 'ltd': np.int64(1224),
 'per msg': np.int64(1543),
 'reply stop': np.int64(1733),
 'stop end': np.int64(1993),
 'begin': np.int64(164),
 'qatar': np.int64(1660),
 'pray': np.int64(1634),
 'hard': np.int64(903),
 'got job': np.int64(849),
 'wine': np.int64(2408),
 'thk': np.int64(2115),
 'shirt': np.int64(1857),
 'sometimes': np.int64(1920),
 'dream': np.int64(560),
 'without': np.int64(2418),
 'joy': np.int64(1056),
 'tv': np.int64(2197),
 'become': np.int64(159),
 'leaving': np.int64(1137),
 'house': np.int64(961),
 'interview': np.int64(1013),
 'boy': np.int64(206),
 'missing': np.int64(1327),
 'arrange': np.int64(90),
 'new year': np.int64(1418),
 'receive cash': np.int64(1698),
 'keep': np.int64(1067),

In [11]:
# Dependent Feature / Output Feature
y = pd.get_dummies(df["label"])

In [12]:
y

        ham   spam
0      True  False
1      True  False
2     False   True
3      True  False
4      True  False
...     ...    ...
5567  False   True
5568   True  False
5569   True  False
5570   True  False
5571   True  False

[5572 rows x 2 columns]

In [13]:
y = y.iloc[:, 0].values

In [14]:
y.shape

(5572,)

In [15]:
y

array([ True,  True, False,  True,  True, False,  True,  True, False, False,  True, False, False,  True,  True, False,  True,  True,  True, False,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True, ...,  True,  True,  True,  True,  True, False,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True, False, False,  True,  True,  True,  True])

In [16]:
# Train Test Split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.20, random_state=0
)

In [17]:
from sklearn.naive_bayes import MultinomialNB

In [18]:
spam_detect_model = MultinomialNB().fit(X_train, y_train)

In [19]:
y_pred = spam_detect_model.predict(X_test)

In [20]:
from sklearn.metrics import accuracy_score, classification_report

In [21]:
accuracy_score(y_test, y_pred)

0.9838565022421525

In [22]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

       False       0.97      0.92      0.94       166
        True       0.99      1.00      0.99       949

    accuracy                           0.98      1115
   macro avg       0.98      0.96      0.97      1115
weighted avg       0.98      0.98      0.98      1115

## Creating The TF-IDF Model

In [23]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [24]:
tv = TfidfVectorizer(
    max_features=2500,
    ngram_range=(1, 2)
)

In [25]:
X = tv.fit_transform(corpus).toarray()

In [26]:
tv.vocabulary_

{'go': np.int64(811),
 'point': np.int64(1614),
 'crazy': np.int64(447),
 'available': np.int64(112),
 'bugis': np.int64(227),
 'great': np.int64(856),
 'world': np.int64(2436),
 'la': np.int64(1096),
 'cine': np.int64(345),
 'got': np.int64(847),
 'wat': np.int64(2336),
 'ok': np.int64(1477),
 'lar': np.int64(1108),
 'joking': np.int64(1053),
 'wif': np.int64(2399),
 'oni': np.int64(1493),
 'free': np.int64(718),
 'entry': np.int64(616),
 'wkly': np.int64(2422),
 'comp': np.int64(401),
 'win': np.int64(2404),
 'cup': np.int64(455),
 'final': np.int64(683),
 'st': np.int64(1961),
 'may': np.int64(1267),
 'text': np.int64(2090),
 'receive': np.int64(1696),
 'question': np.int64(1662),
 'std': np.int64(1979),
 'txt': np.int64(2200),
 'rate': np.int64(1675),
 'apply': np.int64(77),
 'free entry': np.int64(723),
 'entry wkly': np.int64(618),
 'std txt': np.int64(1980),
 'txt rate': np.int64(2204),
 'rate apply': np.int64(1676),
 'dun': np.int64(571),
 'say': np.int64(1796),
 'early': np.int64(581),
 'already': np.int64(51),
 'nah': np.int64(1390),
 'think': np.int64(2110),
 'usf': np.int64(2265),
 'life': np.int64(1154),
 'around': np.int64(88),
 'though': np.int64(2118),
 'freemsg': np.int64(736),
 'hey': np.int64(917),
 'darling': np.int64(479),
 'week': np.int64(2365),
 'word': np.int64(2431),
 'back': np.int64(131),
 'like': np.int64(1159),
 'fun': np.int64(763),
 'still': np.int64(1982),
 'tb': np.int64(2069),
 'xxx': np.int64(2463),
 'send': np.int64(1830),
 'even': np.int64(629),
 'brother': np.int64(217),
 'speak': np.int64(1939),
 'treat': np.int64(2179),
 'per': np.int64(1540),
 'request': np.int64(1740),
 'melle': np.int64(1284),
 'set': np.int64(1847),
 'callertune': np.int64(273),
 'caller': np.int64(270),
 'press': np.int64(1636),
 'copy': np.int64(430),
 'friend': np.int64(743),
 'per request': np.int64(1544),
 'set callertune': np.int64(1848),
 'callertune caller': np.int64(274),
 'caller press': np.int64(271),
 'press copy': np.int64(1637),
 'copy friend': np.int64(431),
 'friend callertune': np.int64(744),
 'winner': np.int64(2409),
 'valued': np.int64(2274),
 'network': np.int64(1406),
 'customer': np.int64(461),
 'selected': np.int64(1822),
 'prize': np.int64(1644),
 'reward': np.int64(1752),
 'claim': np.int64(348),
 'call': np.int64(244),
 'code': np.int64(366),
 'valid': np.int64(2272),
 'hour': np.int64(960),
 'claim call': np.int64(349),
 'call claim': np.int64(248),
 'claim code': np.int64(350),
 'mobile': np.int64(1334),
 'month': np.int64(1353),
 'entitled': np.int64(614),
 'update': np.int64(2230),
 'latest': np.int64(1118),
 'colour': np.int64(380),
 'camera': np.int64(280),
 'co': np.int64(363),
 'entitled update': np.int64(615),
 'update latest': np.int64(2232),
 'latest colour': np.int64(1120),
 'free call': np.int64(721),
 'call mobile': np.int64(258),
 'mobile update': np.int64(1342),
 'update co': np.int64(2231),
 'co free': np.int64(364),
 'gonna': np.int64(832),
 'home': np.int64(944),
 'soon': np.int64(1926),
 'want': np.int64(2321),
 'talk': np.int64(2064),
 'stuff': np.int64(2015),
 'anymore': np.int64(67),
 'tonight': np.int64(2162),
 'enough': np.int64(610),
 'today': np.int64(2146),
 'chance': np.int64(318),
 'cash': np.int64(304),
 'pound': np.int64(1626),
 'cost': np.int64(433),
 'day': np.int64(485),
 'reply': np.int64(1727),
 'hl': np.int64(929),
 'info': np.int64(1001),
 'chance win': np.int64(320),
 'win cash': np.int64(2405),
 'reply hl': np.int64(1731),
 'hl info': np.int64(930),
 'urgent': np.int64(2254),
 'membership': np.int64(1287),
 'www': np.int64(2451),
 'net': np.int64(1404),
 'pobox': np.int64(1610),
 'ldnw': np.int64(1131),
 'week free': np.int64(2367),
 'txt word': np.int64(2206),
 'searching': np.int64(1808),
 'right': np.int64(1754),
 'thank': np.int64(2101),
 'promise': np.int64(1654),
 'wont': np.int64(2430),
 'take': np.int64(2060),
 'help': np.int64(915),
 'wonderful': np.int64(2428),
 'blessing': np.int64(182),
 'time': np.int64(2131),
 'date': np.int64(482),
 'sunday': np.int64(2031),
 'use': np.int64(2262),
 'credit': np.int64(449),
 'click': np.int64(357),
 'wap': np.int64(2333),
 'link': np.int64(1168),
 'next': np.int64(1420),
 'message': np.int64(1293),
 'http': np.int64(969),
 'com': np.int64(383),
 'oh': np.int64(1473),
 'watching': np.int64(2343),
 'eh': np.int64(592),
 'remember': np.int64(1719),
 'name': np.int64(1392),
 'yes': np.int64(2479),
 'naughty': np.int64(1397),
 'make': np.int64(1239),
 'wet': np.int64(2388),
 'fine': np.int64(690),
 'way': np.int64(2348),
 'feel': np.int64(671),
 'england': np.int64(606),
 'dont': np.int64(548),
 'miss': np.int64(1323),
 'goal': np.int64(822),
 'team': np.int64(2074),
 'news': np.int64(1419),
 'ur': np.int64(2233),
 'national': np.int64(1394),
 'eg': np.int64(590),
 'try': np.int64(2188),
 'wq': np.int64(2446),
 'dont miss': np.int64(550),
 'seriously': np.int64(1843),
 'going': np.int64(826),
 'ha': np.int64(883),
 'ha ha': np.int64(884),
 'pay': np.int64(1535),
 'first': np.int64(694),
 'da': np.int64(468),
 'stock': np.int64(1986),
 'comin': np.int64(396),
 'aft': np.int64(26),
 'finish': np.int64(692),
 'lunch': np.int64(1229),
 'str': np.int64(2008),
 'lor': np.int64(1200),
 'ard': np.int64(83),
 'smth': np.int64(1908),
 'alright': np.int64(52),
 'meet': np.int64(1278),
 'eat': np.int64(585),
 'really': np.int64(1691),
 'hungry': np.int64(974),
 'tho': np.int64(2117),
 'suck': np.int64(2024),
 'mark': np.int64(1251),
 'getting': np.int64(798),
 'worried': np.int64(2437),
 'know': np.int64(1089),
 'sick': np.int64(1870),
 'turn': np.int64(2196),
 'pizza': np.int64(1575),
 'lol': np.int64(1188),
 'always': np.int64(55),
 'catch': np.int64(310),
 'bus': np.int64(229),
 'egg': np.int64(591),
 'tea': np.int64(2072),
 'eating': np.int64(587),
 'mom': np.int64(1348),
 'left': np.int64(1139),
 'dinner': np.int64(529),
 'love': np.int64(1206),
 'amp': np.int64(58),
 'car': np.int64(292),
 'let': np.int64(1146),
 'room': np.int64(1765),
 'let know': np.int64(1148),
 'work': np.int64(2432),
 'feel like': np.int64(672),
 'wait': np.int64(2301),
 'sure': np.int64(2043),
 'live': np.int64(1174),
 'yeah': np.int64(2472),
 'child': np.int64(338),
 'till': np.int64(2130),
 'cheer': np.int64(335),
 'yeah got': np.int64(2473),
 'tell': np.int64(2079),
 'anything': np.int64(69),
 'tell anything': np.int64(2080),
 'quick': np.int64(1663),
 'thanks': np.int64(2102),
 'subscription': np.int64(2023),
 'ringtone': np.int64(1757),
 'uk': np.int64(2214),
 'charged': np.int64(326),
 'please': np.int64(1588),
 'confirm': np.int64(411),
 'replying': np.int64(1735),
 'mobile charged': np.int64(1336),
 'yup': np.int64(2498),
 'look': np.int64(1194),
 'timing': np.int64(2137),
 'msg': np.int64(1372),
 'learn': np.int64(1134),
 'nd': np.int64(1398),
 'lesson': np.int64(1145),
 'go home': np.int64(816),
 'oops': np.int64(1497),
 'roommate': np.int64(1766),
 'done': np.int64(547),
 'see': np.int64(1816),
 'letter': np.int64(1149),
 'decide': np.int64(502),
 'anything lor': np.int64(70),
 'hello': np.int64(914),
 'saturday': np.int64(1790),
 'texting': np.int64(2098),
 'decided': np.int64(503),
 'tomo': np.int64(2154),
 'trying': np.int64(2189),
 'pls': np.int64(1594),
 'ahead': np.int64(34),
 'wanted': np.int64(2331),
 'weekend': np.int64(2372),
 'abiola': np.int64(2),
 'great weekend': np.int64(858),
 'forget': np.int64(710),
 'need': np.int64(1402),
 'crave': np.int64(446),
 'sweet': np.int64(2053),
 'want need': np.int64(2326),
 'tried': np.int64(2180),
 'sm': np.int64(1901),
 'nokia': np.int64(1434),
 'camcorder': np.int64(276),
 'delivery': np.int64(512),
 'tomorrow': np.int64(2155),
 'call reply': np.int64(263),
 'free nokia': np.int64(729),
 'nokia mobile': np.int64(1439),
 'mobile free': np.int64(1339),
 'free camcorder': np.int64(722),
 'please call': np.int64(1589),
 'delivery tomorrow': np.int64(513),
 'seeing': np.int64(1819),
 'hope': np.int64(948),
 'man': np.int64(1244),
 'well': np.int64(2380),
 'lt': np.int64(1220),
 'gt': np.int64(863),
 'inch': np.int64(996),
 'lt gt': np.int64(1222),
 'missed': np.int64(1325),
 'missed call': np.int64(1326),
 'get': np.int64(786),
 'nigeria': np.int64(1425),
 'hopefully': np.int64(951),
 'tyler': np.int64(2211),
 'could': np.int64(438),
 'maybe': np.int64(1269),
 'ask': np.int64(97),
 'bit': np.int64(178),
 'hospital': np.int64(955),
 'kept': np.int64(1073),
 'telling': np.int64(2083),
 'weak': np.int64(2357),
 'want go': np.int64(2324),
 'saw': np.int64(1795),
 'class': np.int64(355),
 'first time': np.int64(695),
 'usually': np.int64(2268),
 'run': np.int64(1773),
 'half': np.int64(889),
 'almost': np.int64(48),
 'whole': np.int64(2396),
 'second': np.int64(1811),
 'like lt': np.int64(1162),
 'fyi': np.int64(766),
 'ride': np.int64(1753),
 'morning': np.int64(1358),
 'place': np.int64(1576),
 'wow': np.int64(2445),
 'never': np.int64(1410),
 'thought': np.int64(2119),
 'liked': np.int64(1163),
 'since': np.int64(1879),
 'best': np.int64(168),
 'happy': np.int64(899),
 'sorry': np.int64(1927),
 'give': np.int64(805),
 'ac': np.int64(5),
 'new': np.int64(1411),
 'red': np.int64(1704),
 'play': np.int64(1581),
 'ice': np.int64(980),
 'correct': np.int64(432),
 'end': np.int64(599),
 'sm ac': np.int64(1902),
 'yesterday': np.int64(2485),
 'find': np.int64(686),
 'congrats': np.int64(412),
 'year': np.int64(2475),
 'special': np.int64(1942),
 'cinema': np.int64(346),
 'pas': np.int64(1532),
 'etc': np.int64(625),
 'bx': np.int64(235),
 'ip': np.int64(1020),
 'pm': np.int64(1604),
 'etc free': np.int64(626),
 'bx ip': np.int64(236),
 'ip pm': np.int64(1021),
 'later': np.int64(1115),
 'meeting': np.int64(1280),
 'sorry call': np.int64(1928),
 'call later': np.int64(256),
 'later meeting': np.int64(1116),
 'reached': np.int64(1684),
 'pick': np.int64(1563),
 'move': np.int64(1364),
 'pain': np.int64(1523),
 'way home': np.int64(2350),
 'good': np.int64(834),
 'joke': np.int64(1052),
 'girl': np.int64(804),
 'situation': np.int64(1890),
 'part': np.int64(1528),
 'checking': np.int64(334),
 'iq': np.int64(1024),
 'took': np.int64(2164),
 'forever': np.int64(709),
 'come': np.int64(386),
 'ok come': np.int64(1478),
 'double': np.int64(553),
 'check': np.int64(332),
 'hair': np.int64(888),
 'said': np.int64(1782),
 'wun': np.int64(2450),
 'cut': np.int64(463),
 'short': np.int64(1862),
 'nice': np.int64(1423),
 'pleased': np.int64(1591),
 'following': np.int64(704),
 'review': np.int64(1751),
 'mob': np.int64(1332),
 'awarded': np.int64(120),
 'bonus': np.int64(188),
 'awarded bonus': np.int64(121),
 'prize call': np.int64(1645),
 'song': np.int64(1922),
 'frnds': np.int64(754),
 'rply': np.int64(1771),
 'send ur': np.int64(1836),
 'complimentary': np.int64(406),
 'trip': np.int64(2182),
 'dis': np.int64(533),
 'ur awarded': np.int64(2234),
 'hear': np.int64(908),
 'plane': np.int64(1578),
 'wah': np.int64(2300),
 'lucky': np.int64(1227),
 'save': np.int64(1794),
 'money': np.int64(1352),
 'hee': np.int64(912),
 'finished': np.int64(693),
 'hi': np.int64(921),
 'babe': np.int64(127),
 'im': np.int64(988),
 'wanna': np.int64(2320),
 'something': np.int64(1918),
 'xx': np.int64(2462),
 'hi babe': np.int64(922),
 'waiting': np.int64(2306),
 'call free': np.int64(250),
 'thats': np.int64(2105),
 'cool': np.int64(428),
 'respect': np.int64(1742),
 'thats cool': np.int64(2106),
 'people': np.int64(1539),
 'much': np.int64(1378),
 'pa': np.int64(1518),
 'looking': np.int64(1198),
 'job': np.int64(1046),
 'ta': np.int64(2059),
 'ah': np.int64(32),
 'hi hi': np.int64(924),
 'stop': np.int64(1990),
 'urgnt': np.int64(2260),
 'real': np.int64(1690),
 'yo': np.int64(2491),
 'ticket': np.int64(2128),
 'one': np.int64(1490),
 'used': np.int64(2263),
 'started': np.int64(1972),
 'came': np.int64(278),
 'bed': np.int64(160),
 'coin': np.int64(371),
 'gotta': np.int64(853),
 'kano': np.int64(1064),
 'il': np.int64(986),
 'download': np.int64(555),
 'wen': np.int64(2383),
 'wen ur': np.int64(2384),
 'stand': np.int64(1965),
 'close': np.int64(359),
 'another': np.int64(63),
 'night': np.int64(1426),
 'spent': np.int64(1951),
 'late': np.int64(1114),
 'afternoon': np.int64(27),
 'mean': np.int64(1271),
 'smile': np.int64(1904),
 'pleasure': np.int64(1592),
 'trouble': np.int64(2183),
 'rain': np.int64(1670),
 'sum': np.int64(2028),
 'hurt': np.int64(976),
 'someone': np.int64(1915),
 'smiling': np.int64(1905),
 'service': np.int64(1844),
 'representative': np.int64(1737),
 'guaranteed': np.int64(871),
 'call customer': np.int64(249),
 'customer service': np.int64(462),
 'service representative': np.int64(1846),
 'representative pm': np.int64(1739),
 'pm guaranteed': np.int64(1606),
 'guaranteed cash': np.int64(873),
 'cash prize': np.int64(308),
 'havent': np.int64(906),
 'planning': np.int64(1580),
 'buy': np.int64(232),
 'show': np.int64(1863),
 'simply': np.int64(1878),
 'password': np.int64(1533),
 'free ringtone': np.int64(732),
 'movie': np.int64(1365),
 'abt': np.int64(4),
 'wat abt': np.int64(2337),
 'load': np.int64(1179),
 'loan': np.int64(1180),
 'wk': np.int64(2420),
 'forgot': np.int64(711),
 'appointment': np.int64(78),
 'shower': np.int64(1866),
 'cause': np.int64(311),
 'prob': np.int64(1649),
 'need get': np.int64(1403),
 'get home': np.int64(791),
 'nothing': np.int64(1452),
 'else': np.int64(594),
 'okay': np.int64(1485),
 'price': np.int64(1639),
 'long': np.int64(1191),
 'ave': np.int64(113),
 'gone': np.int64(831),
 'driving': np.int64(564),
 'test': np.int64(2089),
 'yet': np.int64(2486),
 'guess': np.int64(879),
 'gave': np.int64(773),
 'boston': np.int64(198),
 'men': np.int64(1288),
 'changed': np.int64(322),
 'search': np.int64(1807),
 'location': np.int64(1182),
 'cuz': np.int64(465),
 'page': np.int64(1521),
 'umma': np.int64(2216),
 'lot': np.int64(1204),
 'dear': np.int64(498),
 'love lot': np.int64(1210),
 'wish': np.int64(2411),
 'birthday': np.int64(176),
 'making': np.int64(1242),
 'truly': np.int64(2185),
 'aight': np.int64(36),
 'hit': np.int64(927),
 'get cash': np.int64(788),
 'would': np.int64(2443),
 'address': np.int64(18),
 'computer': np.int64(407),
 'old': np.int64(1487),
 'better': np.int64(169),
 'worry': np.int64(2438),
 'busy': np.int64(231),
 'research': np.int64(1741),
 'thing': np.int64(2109),
 'scared': np.int64(1800),
 'mah': np.int64(1235),
 'contact': np.int64(417),
 'last': np.int64(1109),
 'draw': np.int64(556),
 'hr': np.int64(967),
 'ppm': np.int64(1630),
 'trying contact': np.int64(2190),
 'contact last': np.int64(420),
 'last weekend': np.int64(1113),
 'weekend draw': np.int64(2373),
 'draw show': np.int64(558),
 'show prize': np.int64(1864),
 'prize guaranteed': np.int64(1647),
 'guaranteed call': np.int64(872),
 'code valid': np.int64(369),
 'valid hr': np.int64(2273),
 'hr ppm': np.int64(968),
 'wa': np.int64(2299),
 'anyway': np.int64(73),
 'juz': np.int64(1062),
 'tt': np.int64(2192),
 'eatin': np.int64(586),
 'weight': np.int64(2377),
 'haha': np.int64(886),
 'happened': np.int64(895),
 'entered': np.int64(612),
 'cabin': np.int64(238),
 'bos': np.int64(196),
 'felt': np.int64(674),
 'askd': np.int64(98),
 'invited': np.int64(1015),
 'apartment': np.int64(74),
 'went': np.int64(2385),
 'entered cabin': np.int64(613),
 'cabin pa': np.int64(239),
 'pa said': np.int64(1519),
 'said happy': np.int64(1783),
 'happy day': np.int64(901),
 'day bos': np.int64(487),
 'bos felt': np.int64(197),
 'felt special': np.int64(675),
 'special askd': np.int64(1943),
 'askd lunch': np.int64(99),
 'lunch lunch': np.int64(1231),
 'lunch invited': np.int64(1230),
 'invited apartment': np.int64(1016),
 'apartment went': np.int64(75),
 'specially': np.int64(1947),
 'holiday': np.int64(940),
 'flight': np.int64(701),
 'inc': np.int64(995),
 'operator': np.int64(1499),
 'min': np.int64(1304),
 'winner specially': np.int64(2410),
 'specially selected': np.int64(1948),
 'selected receive': np.int64(1823),
 'speak live': np.int64(1940),
 'live operator': np.int64(1176),
 'operator claim': np.int64(1500),
 'must': np.int64(1387),
 'friday': np.int64(742),
 'hmm': np.int64(932),
 'uncle': np.int64(2220),
 'informed': np.int64(1003),
 'paying': np.int64(1537),
 'school': np.int64(1802),
 'directly': np.int64(532),
 'food': np.int64(706),
 'private': np.int64(1642),
 'account': np.int64(9),
 'statement': np.int64(1974),
 'identifier': np.int64(983),
 'expires': np.int64(650),
 'private account': np.int64(1643),
 'account statement': np.int64(10),
 'statement show': np.int64(1975),
 'call identifier': np.int64(252),
 'identifier code': np.int64(984),
 'code expires': np.int64(367),
 'landline': np.int64(1104),
 'box': np.int64(203),
 'urgent mobile': np.int64(2257),
 'mobile awarded': np.int64(1335),
 'bonus caller': np.int64(189),
 'caller prize': np.int64(272),
 'contact call': np.int64(418),
 'call landline': np.int64(255),
 'voda': np.int64(2290),
 'number': np.int64(1459),
 'ending': np.int64(601),
 'award': np.int64(118),
 'match': np.int64(1255),
 'quoting': np.int64(1668),
 'standard': np.int64(1966),
 'app': np.int64(76),
 'today voda': np.int64(2151),
 'voda number': np.int64(2291),
 'number ending': np.int64(1461),
 'ending selected': np.int64(602),
 'receive award': np.int64(1697),
 'match please': np.int64(1256),
 'call quoting': np.int64(262),
 'quoting claim': np.int64(1669),
 'code standard': np.int64(368),
 'standard rate': np.int64(1967),
 'mu': np.int64(1377),
 'buying': np.int64(233),
 'wat time': np.int64(2339),
 'time finish': np.int64(2133),
 'yetunde': np.int64(2488),
 'sent': np.int64(1839),
 'bother': np.int64(199),
 'sending': np.int64(1837),
 'del': np.int64(509),
 'bak': np.int64(138),
 'long time': np.int64(1192),
 'give call': np.int64(806),
 'dear call': np.int64(499),
 'answer': np.int64(65),
 'sunshine': np.int64(2035),
 'quiz': np.int64(1666),
 'top': np.int64(2165),
 'sony': np.int64(1923),
 'dvd': np.int64(578),
 'player': np.int64(1584),
 'country': np.int64(439),
 'sp': np.int64(1936),
 'sunshine quiz': np.int64(2036),
 'sony dvd': np.int64(1924),
 'dvd player': np.int64(579),
 'player know': np.int64(1585),
 'know country': np.int64(1091),
 'sp tyrone': np.int64(1937),
 'laid': np.int64(1100),
 'dogging': np.int64(544),
 'direct': np.int64(531),
 'join': np.int64(1049),
 'bt': np.int64(220),
 'txting': np.int64(2208),
 'nt': np.int64(1454),
 'ec': np.int64(588),
 'want get': np.int64(2323),
 'get laid': np.int64(792),
 'want real': np.int64(2328),
 'sent direct': np.int64(1840),
 'ur mob': np.int64(2245),
 'join uk': np.int64(1050),
 'haf': np.int64(885),
 'yijue': np.int64(2489),
 'chat': np.int64(329),
 'age': np.int64(30),
 'yr': np.int64(2494),
 'go get': np.int64(815),
 'lazy': np.int64(1127),
 'type': np.int64(2212),
 'lect': np.int64(1138),
 'sir': np.int64(1884),
 'mail': np.int64(1237),
 'sir waiting': np.int64(1885),
 'swt': np.int64(2057),
 'tired': np.int64(2138),
 'little': np.int64(1173),
 'lovable': np.int64(1205),
 'person': np.int64(1546),
 'coz': np.int64(443),
 'heart': np.int64(910),
 'gud': np.int64(874),
 'ni': np.int64(1422),
 'gud ni': np.int64(877),
 'open': np.int64(1498),
 'ya': np.int64(2465),
 'yes see': np.int64(2483),
 'whats': np.int64(2391),
 'taking': np.int64(2063),
 'replied': np.int64(1726),
 'sexy': np.int64(1851),
 'local': np.int64(1181),
 'luv': np.int64(1232),
 'ltd': np.int64(1224),
 'per msg': np.int64(1543),
 'reply stop': np.int64(1733),
 'stop end': np.int64(1993),
 'begin': np.int64(164),
 'qatar': np.int64(1660),
 'pray': np.int64(1634),
 'hard': np.int64(903),
 'got job': np.int64(849),
 'wine': np.int64(2408),
 'thk': np.int64(2115),
 'shirt': np.int64(1857),
 'sometimes': np.int64(1920),
 'dream': np.int64(560),
 'without': np.int64(2418),
 'joy': np.int64(1056),
 'tv': np.int64(2197),
 'become': np.int64(159),
 'leaving': np.int64(1137),
 'house': np.int64(961),
 'interview': np.int64(1013),
 'boy': np.int64(206),
 'missing': np.int64(1327),
 'arrange': np.int64(90),
 'new year': np.int64(1418),
 'receive cash': np.int64(1698),
 'keep': np.int64(1067),

In [27]:
# Train Test Split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.20, random_state=0
)

In [28]:
from sklearn.naive_bayes import MultinomialNB
spam_tfidf_model = MultinomialNB().fit(X_train, y_train)

In [29]:
# Prediction
y_pred = spam_tfidf_model.predict(X_test)

In [30]:
score = accuracy_score(y_test, y_pred)
score

0.968609865470852

In [31]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

       False       0.99      0.80      0.88       166
        True       0.97      1.00      0.98       949

    accuracy                           0.97      1115
   macro avg       0.98      0.90      0.93      1115
weighted avg       0.97      0.97      0.97      1115