# Used car Price Prediction

**1) Problem Statement**
- This dataset comprises used cars sold on cardekho.com in india as well as importartant features of these cars.
- If user can predict the price of the car based on the features.
- Prediction result can be used to give new seller the price suggestion basd on market conditions.

**2) Data Collections**
- The dataset is collected from scrapping from cardheko website
- The data consists of 13 column and 15411 rows

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

import warnings
warnings.filterwarnings("ignore")

%matplotlib inline

In [2]:
df = pd.read_csv("cardekho_imputated.csv", index_col=[0])

In [3]:
df.head()

,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,Maruti Alto,Maruti,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,Hyundai Grand,Hyundai,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,Hyundai i20,Hyundai,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,Maruti Alto,Maruti,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,Ford Ecosport,Ford,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000

## Data Collection

### Handling Missing Values

- handling Missing Values
- handling duplicated
- Check data types
- understand the dataset

In [4]:
## Check Null values
## Check features with nan value
df.isnull().sum()

car_name             0
brand                0
model                0
vehicle_age          0
km_driven            0
seller_type          0
fuel_type            0
transmission_type    0
mileage              0
engine               0
max_power            0
seats                0
selling_price        0
dtype: int64

In [5]:
df.head()

,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,Maruti Alto,Maruti,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,Hyundai Grand,Hyundai,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,Hyundai i20,Hyundai,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,Maruti Alto,Maruti,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,Ford Ecosport,Ford,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000

In [6]:
## Remove Unnecessary columns
df.drop('car_name', axis=1, inplace=True)
df.drop('brand', axis=1, inplace=True)

In [7]:
df.head()

,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000

In [8]:
df['model'].unique()

array(['Alto', 'Grand', 'i20', 'Ecosport', 'Wagon R', 'i10', 'Venue',
       'Swift', 'Verna', 'Duster', 'Cooper', 'Ciaz', 'C-Class', 'Innova',
       'Baleno', 'Swift Dzire', 'Vento', 'Creta', 'City', 'Bolero',
       'Fortuner', 'KWID', 'Amaze', 'Santro', 'XUV500', 'KUV100', 'Ignis',
       'RediGO', 'Scorpio', 'Marazzo', 'Aspire', 'Figo', 'Vitara',
       'Tiago', 'Polo', 'Seltos', 'Celerio', 'GO', '5', 'CR-V',
       'Endeavour', 'KUV', 'Jazz', '3', 'A4', 'Tigor', 'Ertiga', 'Safari',
       'Thar', 'Hexa', 'Rover', 'Eeco', 'A6', 'E-Class', 'Q7', 'Z4', '6',
       'XF', 'X5', 'Hector', 'Civic', 'D-Max', 'Cayenne', 'X1', 'Rapid',
       'Freestyle', 'Superb', 'Nexon', 'XUV300', 'Dzire VXI', 'S90',
       'WR-V', 'XL6', 'Triber', 'ES', 'Wrangler', 'Camry', 'Elantra',
       'Yaris', 'GL-Class', '7', 'S-Presso', 'Dzire LXI', 'Aura', 'XC',
       'Ghibli', 'Continental', 'CR', 'Kicks', 'S-Class', 'Tucson',
       'Harrier', 'X3', 'Octavia', 'Compass', 'CLS', 'redi-GO', 'Glanza',
       'Macan', 'X4', 'Dzire ZXI', 'XC90', 'F-PACE', 'A8', 'MUX',
       'GTC4Lusso', 'GLS', 'X-Trail', 'XE', 'XC60', 'Panamera', 'Alturas',
       'Altroz', 'NX', 'Carnival', 'C', 'RX', 'Ghost', 'Quattroporte',
       'Gurkha'], dtype=object)

In [9]:
## Getting All Different Types of features
num_features = [feature for feature in df.columns if df[feature].dtype != 'O']
print("Number of Numerical features: ", len(num_features))

cat_features = [feature for feature in df.columns if df[feature].dtype == 'O']
print("Number of Categorical features: ", len(cat_features))

discerete_features = [feature for feature in num_features if len(df[feature].unique()) < 25]
print("Number of Discerete features: ", len(discerete_features))

continous_features = [feature for feature in num_features if feature not in discerete_features]
print("Number of Continous features: ", len(continous_features))

Number of Numerical features:  7
Number of Categorical features:  4
Number of Discerete features:  2
Number of Continous features:  5

In [10]:
## Independent and Dependent features
from sklearn.model_selection import train_test_split
X = df.drop('selling_price', axis=1)
y = df['selling_price']

In [11]:
df.head()

,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000

## Feature Encoding and Scaling

**One Hot Encoding for columns which has lesser unique and or ordinal**
- One hot encoding is a process by which categorical variables into a form that could be provided to ML algorithms to do a better job in prediction.

In [12]:
len(df['model'].unique())

120

In [13]:
df['model'].value_counts()

model
i20             906
Swift Dzire     890
Swift           781
Alto            778
City            757
               ...
Altroz            1
C                 1
Ghost             1
Quattroporte      1
Gurkha            1
Name: count, Length: 120, dtype: int64

In [14]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X['model'] = le.fit_transform(X['model'])

In [15]:
X.head()

,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats
0,7,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5
1,54,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5
2,118,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5
3,7,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5
4,38,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5

In [16]:
len(df['seller_type'].unique()), len(df['fuel_type'].unique()), len(df['transmission_type'].unique())

(3, 5, 2)

In [17]:
# Create column transformer with 3 types of transformers
num_features = X.select_dtypes(exclude='object').columns
onehot_columns = ['seller_type', 'fuel_type', 'transmission_type']

from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer

numeric_transformer = StandardScaler()
oh_transformer = OneHotEncoder(handle_unknown='ignore', drop='first')

preprocessor = ColumnTransformer(
    [
        ('OneHotEncoder', oh_transformer, onehot_columns),
        ('StandardScaler', numeric_transformer, num_features) 
    ],
    remainder='passthrough'
)

In [18]:
X = preprocessor.fit_transform(X)

In [19]:
X

array([[ 1.        ,  0.        ,  0.        , ..., -1.32425883,
        -1.26335238, -0.40302241],
       [ 1.        ,  0.        ,  0.        , ..., -0.55471774,
        -0.43257082, -0.40302241],
       [ 1.        ,  0.        ,  0.        , ..., -0.55471774,
        -0.47911321, -0.40302241],
       ...,
       [ 0.        ,  0.        ,  1.        , ...,  0.02291783,
         0.06822523, -0.40302241],
       [ 0.        ,  0.        ,  1.        , ...,  1.32979434,
         0.91715831,  2.07344426],
       [ 0.        ,  0.        ,  0.        , ...,  0.02099878,
         0.39588361, -0.40302241]], shape=(15411, 14))

In [20]:
pd.DataFrame(X)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,-1.519714,0.983562,1.247335,-0.000276,-1.324259,-1.263352,-0.403022
1,1.0,0.0,0.0,0.0,0.0,1.0,1.0,-0.225693,-0.343933,-0.690016,-0.192071,-0.554718,-0.432571,-0.403022
2,1.0,0.0,0.0,0.0,0.0,1.0,1.0,1.536377,1.647309,0.084924,-0.647583,-0.554718,-0.479113,-0.403022
3,1.0,0.0,0.0,0.0,0.0,1.0,1.0,-1.519714,0.983562,-0.360667,0.292211,-0.936610,-0.779312,-0.403022
4,0.0,0.0,1.0,0.0,0.0,0.0,1.0,-0.666211,-0.012060,-0.496281,0.735736,0.022918,-0.046502,-0.403022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15406,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.508844,0.983562,-0.869744,0.026096,-0.767733,-0.757204,-0.403022
15407,0.0,0.0,0.0,0.0,0.0,1.0,1.0,-0.556082,-1.339555,-0.728763,-0.527711,-0.216964,-0.220803,2.073444
15408,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.407551,-0.012060,0.220539,0.344954,0.022918,0.068225,-0.403022
15409,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.426247,-0.343933,72.541850,-0.887326,1.329794,0.917158,2.073444
15410,0.0,0.0,0.0,0.0,0.0,1.0,0.0,-1.024131,-1.339555,-0.825631,-0.407839,0.020999,0.395884,-0.403022

In [21]:
# Seperate Train and Test data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
X_train.shape, X_test.shape

((12328, 14), (3083, 14))

In [22]:
X_train

array([[ 0.        ,  0.        ,  1.        , ...,  1.75390551,
         2.66249771, -0.40302241],
       [ 1.        ,  0.        ,  0.        , ..., -0.55087963,
        -0.38602844, -0.40302241],
       [ 0.        ,  0.        ,  1.        , ...,  0.89033072,
         3.27453006, -0.40302241],
       ...,
       [ 1.        ,  0.        ,  0.        , ..., -0.9366097 ,
        -0.78070786, -0.40302241],
       [ 0.        ,  0.        ,  0.        , ..., -0.55471774,
        -0.43582879, -0.40302241],
       [ 1.        ,  0.        ,  0.        , ..., -0.04616815,
         0.06194201, -0.40302241]], shape=(12328, 14))

In [23]:
pd.DataFrame(X_train)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.261053,0.319814,0.283541,-2.038093,1.753906,2.662498,-0.403022
1,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.793003,-1.339555,-0.883751,0.992261,-0.550880,-0.386028,-0.403022
2,0.0,0.0,1.0,0.0,0.0,0.0,0.0,-1.244390,-1.339555,-0.961245,-0.168096,0.890331,3.274530,-0.403022
3,0.0,0.0,0.0,0.0,0.0,1.0,1.0,-1.024131,0.319814,0.143045,-0.455788,0.020999,0.388902,-0.403022
4,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.508844,1.315436,0.478051,0.157955,-0.554718,-0.504712,-0.403022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12323,0.0,0.0,1.0,0.0,0.0,0.0,1.0,-0.556082,0.319814,1.397111,0.256249,-0.456846,-0.274327,2.073444
12324,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.903133,1.647309,0.065551,-0.865749,0.214823,0.060778,-0.403022
12325,1.0,0.0,0.0,0.0,0.0,1.0,1.0,1.040794,0.319814,-0.690016,0.193916,-0.936610,-0.780708,-0.403022
12326,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.536377,-1.339555,-0.786884,-0.263994,-0.554718,-0.435829,-0.403022
12327,1.0,0.0,0.0,0.0,0.0,1.0,0.0,-1.051664,-1.339555,-0.496281,0.138775,-0.046168,0.061942,-0.403022

## Model Training And Model Selection

In [24]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

In [25]:
def evaluate_model(true, predicted):
    mae = mean_absolute_error(true, predicted)
    mse = mean_squared_error(true, predicted)
    rmse = np.sqrt(mean_squared_error(true, predicted))
    r2_square = r2_score(true, predicted)

    return mae, mse, rmse, r2_square

In [26]:
## Beginning Model Training
models = {
    'Linear Regression': LinearRegression(),
    'Ridge': Ridge(),
    'Lasso': Lasso(),
    'K-neighbors Regression': KNeighborsRegressor(),
    'Decision tree': DecisionTreeRegressor(),
    'Random Forest Regression': RandomForestRegressor()
}

for i in range(len(list(models))):
        model = list(models.values())[i]
        model_name = list(models.keys())[i]
        model.fit(X_train, y_train) # Training the model
        
        # make Predictions
        y_train_pred = model.predict(X_train)
        y_test_pred = model.predict(X_test)
        
        # Evaluate Train and Test data
        train_mae, train_mse, train_rmse, train_r2_square = evaluate_model(y_train, y_train_pred)
        test_mae, test_mse, test_rmse, test_r2_square = evaluate_model(y_test, y_test_pred)
        
        print(model_name)
        print("Train Data: ")
        print("MAE: ", train_mae)
        print("MSE: ", train_mse)
        print("RMSE: ", train_rmse)
        print("R2 Square: ", train_r2_square)
        
        print("Test Data: ")
        print("MAE: ", test_mae)
        print("MSE: ", test_mse)
        print("RMSE: ", test_rmse)
        print("R2 Square: ", test_r2_square)

Linear Regression
Train Data:
MAE:  268101.6070829937
MSE:  306756099359.7596
RMSE:  553855.6665411663
R2 Square:  0.6217719576765959
Test Data:
MAE:  279618.5794158427
MSE:  252550062888.56552
RMSE:  502543.59302309836
R2 Square:  0.6645109298852006
Ridge
Train Data:
MAE:  268059.8014688312
MSE:  306756818740.9266
RMSE:  553856.3159709624
R2 Square:  0.6217710706848424
Test Data:
MAE:  279557.2168930274
MSE:  252540243247.9687
RMSE:  502533.82298902894
R2 Square:  0.6645239743566809
Lasso
Train Data:
MAE:  268099.22264981153
MSE:  306756104248.3742
RMSE:  553855.6709544231
R2 Square:  0.6217719516489696
Test Data:
MAE:  279614.7461034126
MSE:  252549134806.7813
RMSE:  502542.66963789385
R2 Square:  0.6645121627547996
K-neighbors Regression
Train Data:
MAE:  91425.47047371836
MSE:  106193217845.55484
RMSE:  325873.008771139
R2 Square:  0.8690645337531115
Test Data:
MAE:  112526.34609146934
MSE:  64021344520.150826
RMSE:  253024.39510875393
R2 Square:  0.9149536488136147
Decision tree
Train Data:
MAE:  5164.819922128488
MSE:  432524990.53644824
RMSE:  20797.23516567643
R2 Square:  0.9994666998284044
Test Data:
MAE:  124515.39896204995
MSE:  93348552313.06538
RMSE:  305529.9532174634
R2 Square:  0.8759952040641882
Random Forest Regression
Train Data:
MAE:  39756.982995004495
MSE:  16296511952.21317
RMSE:  127657.79236777192
R2 Square:  0.9799065191360491
Test Data:
MAE:  101419.61825497454
MSE:  49338722942.09305
RMSE:  222123.2156756539
R2 Square:  0.9344581343945333

In [27]:
## Initialise parameter distributions for Hyperparameter Tuning
knn_params = {
    'n_neighbors': [2, 3, 10, 20, 50],
}
rf_params = {
    'max_depth': [5, 8, 10, 15, None],
    'max_features': ['sqrt', 'log2', None, 0.8],
    'min_samples_split': [2, 8, 15, 20],
    'n_estimators': [100, 200, 500, 1000]
}

In [28]:
# Models list for Hyperparameter Tuning
randomcv_models = [
    ('KNN', KNeighborsRegressor(), knn_params),
    ('RF', RandomForestRegressor(), rf_params)
]

In [29]:
# Hyperparameter Tuning using RandomizedSearchCV
from sklearn.model_selection import RandomizedSearchCV

model_params = {}

for name, model, params in randomcv_models:
    # Keep n_iter within the available search space to avoid warnings and wasted runs
    max_iter = np.prod([len(v) for v in params.values()])
    n_iter = min(30, max_iter)

    randomcv = RandomizedSearchCV(
        estimator=model,
        param_distributions=params,
        cv=3,
        n_iter=n_iter,
        n_jobs=-1,
        verbose=2,
        random_state=42,
        scoring='r2'
    )

    randomcv.fit(X_train, y_train)
    model_params[name] = {
        'best_params': randomcv.best_params_,
        'best_score': randomcv.best_score_
    }

for model_name, result in model_params.items():
    print(f"{model_name}: {result['best_params']}")
    print(f"Best CV R2: {result['best_score']:.4f}")

Fitting 3 folds for each of 5 candidates, totalling 15 fits

Fitting 3 folds for each of 30 candidates, totalling 90 fits
KNN: {'n_neighbors': 10}
Best CV R2: 0.7770
RF: {'n_estimators': 100, 'min_samples_split': 2, 'max_features': 0.8, 'max_depth': 15}
Best CV R2: 0.8581

In [31]:
models = {
    'Random Forest Regressor': RandomForestRegressor(
        n_estimators=100,
        min_samples_split=2,
        max_features=0.8,
        max_depth=None,
        n_jobs=-1,
    ),
    'K-Neighbors Regression': KNeighborsRegressor(
        n_neighbors=10,
        n_jobs=-1
    )
}

for i in range(len(list(models))):
        model = list(models.values())[i]
        model_name = list(models.keys())[i]
        model.fit(X_train, y_train) # Training the model
        
        # make Predictions
        y_train_pred = model.predict(X_train)
        y_test_pred = model.predict(X_test)
        
        # Evaluate Train and Test data
        train_mae, train_mse, train_rmse, train_r2_square = evaluate_model(y_train, y_train_pred)
        test_mae, test_mse, test_rmse, test_r2_square = evaluate_model(y_test, y_test_pred)
        
        print(model_name)
        print("Train Data: ")
        print("MAE: ", train_mae)
        print("MSE: ", train_mse)
        print("RMSE: ", train_rmse)
        print("R2 Square: ", train_r2_square)
        
        print("Test Data: ")
        print("MAE: ", test_mae)
        print("MSE: ", test_mse)
        print("RMSE: ", test_rmse)
        print("R2 Square: ", test_r2_square)

Random Forest Regressor
Train Data:
MAE:  39465.53187166095
MSE:  13809268542.99639
RMSE:  117512.84416180382
R2 Square:  0.9829732721929999
Test Data:
MAE:  100502.54069839053
MSE:  52073580944.203964
RMSE:  228196.36487946947
R2 Square:  0.9308251320601445
K-Neighbors Regression
Train Data:
MAE:  103472.04737183647
MSE:  132103731766.70993
RMSE:  363460.7706021517
R2 Square:  0.8371170582947722
Test Data:
MAE:  117496.21310411936
MSE:  69636909424.46481
RMSE:  263888.06230003055
R2 Square:  0.9074938975612508